teams:
    world:
        world:
            display: 'World'
            prefix: 'ยง2'
            suffix: ''
        world_nether:
            display: 'Nether'
            prefix: 'ยง4'
            suffix: ''
        world_the_end:
            display: 'The End'
            prefix: 'ยง1'
            suffix: ''
objectives:
    serverstats:
        update: 100
defaults:
    teams: 'ScoreShare.worlds'
    below_name:
    player_list: 
    sidebar: 'ScoreShare.serverStats'
